/////////////////////////////////////////////////////////////////////////////////////
//  File: EidoDereferenceFactoryQueryResponseLogEvent.cs            5 May 23 PHR
/////////////////////////////////////////////////////////////////////////////////////

namespace I3V3.LogEvents;

/// <summary>
/// Logged when a response to an EIDO Dereference Factory request is sent or received. See Section 2.9.3
/// of NENA-STA-024.1a-2023.
/// </summary>
public class EidoDereferenceFactoryQueryResponseLogEvent : LogEvent
{
    /// <summary>
    /// For the server (direction = "outgoing") set to the client's ID. For the client (direction =
    /// "incoming", set to the ID of the server. Required.
    /// </summary>
    public string peerId { get; set; }

    /// <summary>
    /// Sets or gets the query ID. Unique ID used for matching a response to the query. See Section 2.9 of
    /// NENA-STA-024.1a-2023.
    /// Required.
    /// </summary>
    public string queryId { get; set; }

    /// <summary>
    /// Must be set to "incoming" or "outgoing". Required
    /// </summary>
    public string direction { get; set; }

    /// <summary>
    /// Identifies the URI that was generated by the EIDO Dereference Factory. Required if no error
    /// occurred and the responseError property is not set.
    /// </summary>
    public string generatedURI { get; set; }

    /// <summary>
    /// Set to an error code from the Error Codes Registry in the case of an error. Required if the 
    /// generatedURI property is not set.
    /// </summary>
    public string responseError { get; set; }

    /// <summary>
    /// Set to text that describes the responseError.
    /// </summary>
    public string responseText { get; set; }

    /// <summary>
    /// Constructor
    /// </summary>
    public EidoDereferenceFactoryQueryResponseLogEvent()
    {
        logEventType = "EidoDereferenceFactoryQueryResponseLogEvent";
    }
}
