//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 

/////////////////////////////////////////////////////////////////////////////////////
//  Revised:  15 Mar 23 PHR
//              -- Simplified the XML namespaces and attributes
//              -- Added documentation comments
/////////////////////////////////////////////////////////////////////////////////////

using System.Xml;
using System.Xml.Serialization;

namespace AdditionalData {

    /// <summary>
    /// Data class for the DeviceInfo additional data. This block provides information about the device 
    /// used to place the call.
    /// See Section 4.3 of RFC 7852.
    /// </summary>
    [Serializable()]
    [XmlType(Namespace="urn:ietf:params:xml:ns:EmergencyCallData:DeviceInfo")]
    [XmlRoot("EmergencyCallData.DeviceInfo", Namespace="urn:ietf:params:xml:ns:EmergencyCallData:DeviceInfo",
        IsNullable=false)]
    public partial class DeviceInfoType {
        
        private string dataProviderReferenceField;
        private string deviceClassificationField;
        private string deviceMfgrField;
        private string deviceModelNrField;
        private DeviceInfoTypeUniqueDeviceID[] uniqueDeviceIDField;
        private string deviceSpecificDataField;
        private string deviceSpecificTypeField;
        private System.Xml.XmlElement[] anyField;

        /// <summary>
        /// Identifies the provider (data provider) of this block. Should match the DataProviderReference
        /// element of a ProviderInfo additional data block.
        /// </summary>
        [XmlElement(DataType="token")]
        public string DataProviderReference {
            get {
                return this.dataProviderReferenceField;
            }
            set {
                this.dataProviderReferenceField = value;
            }
        }

        /// <summary>
        /// Defines the kind of device making the emergency call. See Section 4.3.1 of RFC 7852.
        /// This field should be set to one of the values listed in Figure 8 of RFC 7852.
        /// </summary>
        public string DeviceClassification {
            get {
                return this.deviceClassificationField;
            }
            set {
                this.deviceClassificationField = value;
            }
        }

        /// <summary>
        /// Contains the plain language name of the manufacturer of the device. See Section 4.3.2 or 
        /// RFC 7852.
        /// </summary>
        public string DeviceMfgr {
            get {
                return this.deviceMfgrField;
            }
            set {
                this.deviceMfgrField = value;
            }
        }
        
        /// <summary>
        /// Contains the Device Model Number. See Section 4.3.3 or RFC 7852.
        /// </summary>
        public string DeviceModelNr {
            get {
                return this.deviceModelNrField;
            }
            set {
                this.deviceModelNrField = value;
            }
        }
        
        /// <summary>
        /// Contains an array of unique device identifiers. See Section 4.3 of RFC 7852.
        /// </summary>
        [XmlElement("UniqueDeviceID")]
        public DeviceInfoTypeUniqueDeviceID[] UniqueDeviceID {
            get {
                return this.uniqueDeviceIDField;
            }
            set {
                this.uniqueDeviceIDField = value;
            }
        }

        /// <summary>
        /// Contains an URI representing additional data whose schema is specific to the device or service 
        /// that created it. The URI, when dereferenced, MUST yield a data structure defined by the 
        /// DeviceSpecificType property. 
        /// See Section 4.3.5 of RFC 7852.
        /// </summary>
        [XmlElement(DataType="anyURI")]
        public string DeviceSpecificData {
            get {
                return this.deviceSpecificDataField;
            }
            set {
                this.deviceSpecificDataField = value;
            }
        }

        /// <summary>
        /// Contains a value from the registry defined in Section 11.1.8 of RFC 7852 to describe the type 
        /// of data located at the URI specified in the DeviceSpecificData element.
        /// </summary>
        /// <remarks>The only value defined for this element is IEEE1512.
        /// See: https://standards.ieee.org/ieee/1512/3522/ for the standard that describes the schema
        /// of the data.</remarks>
        public string DeviceSpecificType {
            get {
                return this.deviceSpecificTypeField;
            }
            set {
                this.deviceSpecificTypeField = value;
            }
        }
        
        /// <summary>
        /// Extension point for this class
        /// </summary>
        [XmlAnyElement()]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
    }
    
    /// <summary>
    /// This data class information that uniquely identifies a device that made an emergency call.
    /// See Section 4.3.4 of RFC 7852.
    /// </summary>
    [Serializable()]
    [XmlType(AnonymousType=true, Namespace="urn:ietf:params:xml:ns:EmergencyCallData:DeviceInfo")]
    public partial class DeviceInfoTypeUniqueDeviceID {
        
        private string typeOfDeviceIDField;
        private string valueField;

        /// <summary>
        /// This attribute identifies the type of device identifier. The values are limited to those
        /// specified in Figure 9 of RFC 7852.
        /// </summary>
        [XmlAttribute()]
        public string TypeOfDeviceID {
            get {
                return this.typeOfDeviceIDField;
            }
            set {
                this.typeOfDeviceIDField = value;
            }
        }
        
        /// <summary>
        /// Specifies the device ID. The type of value is specified by the value of the TypeOfDeviceID
        /// attribute.
        /// </summary>
        [XmlText()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
}
