//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 

/////////////////////////////////////////////////////////////////////////////////////
// Revised: 19 Jul 16 PHR
//            -- Added the ProvidedByType class. Added namespaces
//               to each of the elements in the EmergencyCallDataValueType class.
//          15 Mar 13 PHR
//            -- Simplified the XML namespaces and attributes
//            -- Added more documentation comments
/////////////////////////////////////////////////////////////////////////////////////

using System.Xml;
using System.Xml.Serialization;

namespace AdditionalData {

    /// <summary>
    /// Class for the provided-by element of a geopriv element. This class is for providing additional 
    /// data by value or by reference with a provided-by element. See RFC 7852.
    /// </summary>
    [Serializable()]
    [XmlType(Namespace = "urn:ietf:params:xml:ns:EmergencyCallData")]
    [XmlRoot("provided-by", Namespace = "urn:ietf:params:xml:ns:EmergencyCallData", IsNullable = false)]
    public partial class ProvidedByType
    {
        /// <summary>
        /// Contains addition elements by value
        /// </summary>
        [XmlElement]
        public EmergencyCallDataValueType EmergencyCallDataValue;

        /// <summary>
        /// Contains a list of references to additional data
        /// </summary>
        [XmlElement]
        public List<ByRefType> EmergencyCallDataReference;
    }

    /// <summary>
    /// Container class for passing additional data by value
    /// </summary>
    [Serializable()]
    [XmlType(Namespace="urn:ietf:params:xml:ns:EmergencyCallData")]
    [XmlRoot("EmergencyCallDataValue", Namespace="urn:ietf:params:xml:ns:EmergencyCallData", 
        IsNullable=false)]
    public partial class EmergencyCallDataValueType {
        
        private ProviderInfoType[] emergencyCallDataProviderInfoField;
        private ServiceInfoType[] emergencyCallDataServiceInfoField;
        private DeviceInfoType[] emergencyCallDataDeviceInfoField;
        private SubscriberInfoType[] emergencyCallDataSubscriberInfoField;
        private CommentType[] emergencyCallDataCommentField;
        private XmlElement[] anyField;
        
        /// <summary>
        /// Contains an array of ProviderInfoType objects for additional data providers
        /// </summary>
        [XmlElement("EmergencyCallData.ProviderInfo", Namespace = 
            "urn:ietf:params:xml:ns:EmergencyCallData:ProviderInfo")]
        public ProviderInfoType[] EmergencyCallDataProviderInfo {
            get {
                return this.emergencyCallDataProviderInfoField;
            }
            set {
                this.emergencyCallDataProviderInfoField = value;
            }
        }
        
        /// <summary>
        /// Service information for the call
        /// </summary>
        [XmlElement("EmergencyCallData.ServiceInfo",
            Namespace = "urn:ietf:params:xml:ns:EmergencyCallData:ServiceInfo")]
        public ServiceInfoType[] EmergencyCallDataServiceInfo {
            get {
                return this.emergencyCallDataServiceInfoField;
            }
            set {
                this.emergencyCallDataServiceInfoField = value;
            }
        }
        
        /// <summary>
        /// Device information about the device from which the emergency call was made
        /// </summary>
        [XmlElement("EmergencyCallData.DeviceInfo",
            Namespace = "urn:ietf:params:xml:ns:EmergencyCallData:DeviceInfo")]
        public DeviceInfoType[] EmergencyCallDataDeviceInfo {
            get {
                return this.emergencyCallDataDeviceInfoField;
            }
            set {
                this.emergencyCallDataDeviceInfoField = value;
            }
        }
        
        /// <summary>
        /// Contains information about the subscriber of the service
        /// </summary>
        [XmlElement("EmergencyCallData.SubscriberInfo",
            Namespace = "urn:ietf:params:xml:ns:EmergencyCallData:SubscriberInfo")]
        public SubscriberInfoType[] EmergencyCallDataSubscriberInfo {
            get {
                return this.emergencyCallDataSubscriberInfoField;
            }
            set {
                this.emergencyCallDataSubscriberInfoField = value;
            }
        }
        
        /// <summary>
        /// Comments that may relate to any of the other additional data blocks
        /// </summary>
        [XmlElement("EmergencyCallData.Comment",
            Namespace = "urn:ietf:params:xml:ns:EmergencyCallData:Comment")]
        public CommentType[] EmergencyCallDataComment {
            get {
                return this.emergencyCallDataCommentField;
            }
            set {
                this.emergencyCallDataCommentField = value;
            }
        }
        
        /// <summary>
        /// Extension point for this class
        /// </summary>
        [XmlAnyElement()]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
    }
    
    /// <summary>
    /// Data class for passing additional data by reference
    /// </summary>
    [Serializable()]
    [XmlType(Namespace="urn:ietf:params:xml:ns:EmergencyCallData")]
    [XmlRoot("EmergencyCallDataReference", Namespace="urn:ietf:params:xml:ns:EmergencyCallData", 
        IsNullable=false)]
    public partial class ByRefType {
        
        private System.Xml.XmlElement[] anyField;
        private string purposeField;
        private string refField;
        
        /// <summary>
        /// Extension point for this class
        /// </summary>
        [XmlAnyElement()]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }

        /// <summary>
        /// Purpose attribute that indicates the type data returned when the URI in the ref attribute
        /// is dereferenced. The allowed values are: EmergencyCallData.ServiceInfo,
        /// EmergencyCallData.SubscriberInfo, EmergencyCallData.ProviderInfo, EmergencyCallData.
        /// DeviceInfo and EmergencyCallData.Comment.
        /// </summary>
        [XmlAttribute(DataType="token")]
        public string purpose {
            get {
                return this.purposeField;
            }
            set {
                this.purposeField = value;
            }
        }

		/// <summary>
        /// Contains a URI to dereference to get the additional data.
        /// </summary>
		[XmlAttribute(DataType = "anyURI")]
		public string @ref
		{
			get { return this.refField; }
			set { this.refField = value; }
		}
	}   
}
