//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 

/////////////////////////////////////////////////////////////////////////////////////
//  Revised:  15 Mar 23 PHR
//              -- Simplified the XML namespaces and attributes
//              -- Added documentation comments
/////////////////////////////////////////////////////////////////////////////////////

using System.Xml;
using System.Xml.Serialization;

namespace AdditionalData {
    
    /// <summary>
    /// Data class for the ProviderInfo additional data. See Section 4.1 of RFC 7852.
    /// </summary>
    [Serializable()]
	[XmlType(Namespace = "urn:ietf:params:xml:ns:EmergencyCallData:ProviderInfo")]
    [XmlRoot("EmergencyCallData.ProviderInfo", Namespace="urn:ietf:params:xml:ns:EmergencyCallData:ProviderInfo", 
        IsNullable=false)]
    public partial class ProviderInfoType {
        
        private string dataProviderReferenceField;
        private string dataProviderStringField;
        private string providerIDField;
        private string providerIDSeriesField;
        private string typeOfProviderField;
        private string contactURIField;
        private string[] languageField;
        private vcardType[] dataProviderContactField;
        private string subcontractorPrincipalField;
        private SubcontractorPriorityType subcontractorPriorityField;
        private bool subcontractorPriorityFieldSpecified;
        private System.Xml.XmlElement[] anyField;
        
        /// <summary>
        /// Reference string that is used in other additional data blocks to identify the provider of
        /// the additional data.
        /// </summary>
        [XmlElement(DataType="token")]
        public string DataProviderReference {
            get {
                return this.dataProviderReferenceField;
            }
            set {
                this.dataProviderReferenceField = value;
            }
        }

        /// <summary>
        /// Contains a plaintext string suitable for displaying the name of the service provider that 
        /// supplied the data structure
        /// </summary>
        public string DataProviderString {
            get {
                return this.dataProviderStringField;
            }
            set {
                this.dataProviderStringField = value;
            }
        }
        
        /// <summary>
        /// Identifies the provider of the additonal data. The type of ID is specified in the 
        /// ProviderIDSeries element.
        /// </summary>
        public string ProviderID {
            get {
                return this.providerIDField;
            }
            set {
                this.providerIDField = value;
            }
        }

        /// <summary>
        /// Identifies the issuer of the ID in the ProviderID element. Should be one of the values
        /// listed in Table 1 of RFC 7852.
        /// </summary>
        public string ProviderIDSeries {
            get {
                return this.providerIDSeriesField;
            }
            set {
                this.providerIDSeriesField = value;
            }
        }

        /// <summary>
        /// Identifies the type of data provider supplying the data. Should be set to one of the values
        /// listed in Figure 2 in Section 4.1.4 of RFC 7852.
        /// </summary>
        public string TypeOfProvider {
            get {
                return this.typeOfProviderField;
            }
            set {
                this.typeOfProviderField = value;
            }
        }
        
        /// <summary>
        /// When provided by a service provider, should contain a URI to a 24/7 support organization tasked
        /// to provide PSAP support for this emergency call.When provided by a device, this MUST be 
        /// the contact information of the user or owner of the device.URI to a 24/7 support organization
        /// tasked to provide PSAP support for this emergency call. When provided by a device, this MUST be
        /// the contact information of the user or owner of the device.
        /// See Section 4.1.5 of RFC 7852.
        /// </summary>
        [XmlElement(DataType="anyURI")]
        public string ContactURI {
            get {
                return this.contactURIField;
            }
            set {
                this.contactURIField = value;
            }
        }

        /// <summary>
        /// Contains the languages used by the entity at the Data Provider Contact URI. For example: en-US.
        /// See Section 4.1.6 of RFC 7852.
        /// </summary>
        [XmlElement("Language")]
        public string[] Language {
            get {
                return this.languageField;
            }
            set {
                this.languageField = value;
            }
        }

        /// <summary>
        /// Contains the vCard (xCard) of the data provider. Although multiple vcard elements can  be 
        /// contained in a structure, only one vcard element SHOULD be provided.
        /// See Section 4.1.7 of RFC 7852.
        /// </summary>
        [XmlArrayItem("vcard", Namespace="urn:ietf:params:xml:ns:vcard-4.0", IsNullable=false)]
        public vcardType[] DataProviderContact {
            get {
                return this.dataProviderContactField;
            }
            set {
                this.dataProviderContactField = value;
            }
        }

        /// <summary>
        /// If the data provider is a subcontractor to another provider, this element contains the 
        /// DataProviderString of the service provider to indicate which provider the subcontractor is 
        /// working for.
        /// See Section 4.1.8 of RFC 7852.
        /// </summary>
        public string SubcontractorPrincipal {
            get {
                return this.subcontractorPrincipalField;
            }
            set {
                this.subcontractorPrincipalField = value;
            }
        }

        /// <summary>
        /// If the subcontractor is supposed to be contacted first, then this element MUST have the value 
        /// ’sub’. If the provider the subcontractor is working for is supposed to be contacted first,
        /// then this element MUST have the value ’main’.
        /// </summary>
        public SubcontractorPriorityType SubcontractorPriority {
            get {
                return this.subcontractorPriorityField;
            }
            set {
                this.subcontractorPriorityField = value;
            }
        }
        
        /// <summary>
        /// Set to true if the SubcontractorPriorityType property has been set.
        /// </summary>
        [XmlIgnore()]
        public bool SubcontractorPrioritySpecified {
            get {
                return this.subcontractorPriorityFieldSpecified;
            }
            set {
                this.subcontractorPriorityFieldSpecified = value;
            }
        }
        
        /// <summary>
        /// Element extension point for this class.
        /// </summary>
        [XmlAnyElement()]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
    }

    /// <summary>
    /// Enumeration of values for the SubcontractorPriority property of the ProviderInfoType elass.
    /// </summary>
    [Serializable()]
    [XmlType(Namespace="urn:ietf:params:xml:ns:EmergencyCallData:ProviderInfo")]
    public enum SubcontractorPriorityType {
        
        /// <summary>
        /// Indicates that the subcontractor is to be contacted first.
        /// </summary>
        sub,
        
        /// <summary>
        /// The provider that the subcontrator is working for is to be contacted first.
        /// </summary>
        main,
    }
}
