//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
//

/////////////////////////////////////////////////////////////////////////////////////
//  Revised:  16 Mar 23 PHR
//              -- Simplified the XML namespaces and attributes
//              -- Added documentation comments
/////////////////////////////////////////////////////////////////////////////////////

using Pidf;
using System.Xml.Serialization;

namespace AdditionalData {
    
    /// <summary>
    /// Data class for the additional data ServiceInfo block of data. Provides information about the
    /// class and type of telephone service.
    /// See Section 4.2 of RFC 7852.
    /// </summary>
    [Serializable()]
    [XmlType(Namespace="urn:ietf:params:xml:ns:EmergencyCallData:ServiceInfo")]
    [XmlRoot("EmergencyCallData.ServiceInfo", Namespace="urn:ietf:params:xml:ns:EmergencyCallData:ServiceInfo",
        IsNullable=false)]
    public partial class ServiceInfoType {
        
        private string dataProviderReferenceField;
        private string serviceEnvironmentField;
        private string[] serviceTypeField;
        private string serviceMobilityField;
        private System.Xml.XmlElement[] anyField;

        /// <summary>
        /// Identifies the provider (data provider) of this block. Should match the DataProviderReference
        /// element of a ProviderInfo additional data block.
        /// </summary>
        [XmlElement(DataType="token")]
        public string DataProviderReference {
            get {
                return this.dataProviderReferenceField;
            }
            set {
                this.dataProviderReferenceField = value;
            }
        }

        /// <summary>
        /// This element indicates whether a call is from a business or residence.Currently, the only
        /// valid entries are ’Business’, ’Residence’, and ’Unknown’. See Figure 4 of RFC 7852.
        /// </summary>
        public string ServiceEnvironment {
            get {
                return this.serviceEnvironmentField;
            }
            set {
                this.serviceEnvironmentField = value;
            }
        }

        /// <summary>
        /// This defines the type of service over which the call is placed. See Figure 5 of RFC 7852 for
        /// a list of allowed values.
        /// </summary>
        [XmlElement("ServiceType")]
        public string[] ServiceType {
            get {
                return this.serviceTypeField;
            }
            set {
                this.serviceTypeField = value;
            }
        }

        /// <summary>
        /// This provides the service provider’s view of the mobility of the caller’s device.
        /// See Figure 6 of RFC 7852 for a list of allowed values.
        /// </summary>
        public string ServiceMobility {
            get {
                return this.serviceMobilityField;
            }
            set {
                this.serviceMobilityField = value;
            }
        }
        
        /// <summary>
        /// Extension point for this class
        /// </summary>
        [XmlAnyElement()]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
    }
}    
