//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
//

/////////////////////////////////////////////////////////////////////////////////////
//  Revised:  15 Mar 23 PHR
//              -- Simplified the XML namespaces and attributes
//              -- Added documentation comments
/////////////////////////////////////////////////////////////////////////////////////

using System.Xml.Serialization;

namespace AdditionalData {
    
    /// <summary>
    /// Data class for the SubscriberInfo additional data block. This class contains information about
    /// the telephone service subscriber. See Section 4.4 of RFC 7852.
    /// </summary>
    [Serializable()]
    [XmlType(Namespace="urn:ietf:params:xml:ns:EmergencyCallData:SubscriberInfo")]
    [XmlRoot("EmergencyCallData.SubscriberInfo", 
        Namespace="urn:ietf:params:xml:ns:EmergencyCallData:SubscriberInfo", IsNullable=false)]
    public partial class SubscriberInfoType {
        
        private string dataProviderReferenceField;
        private vcardType[] subscriberDataField;
        private System.Xml.XmlElement[] anyField;
        private bool privacyRequestedField;

        /// <summary>
        /// Identifies the provider (data provider) of this block. Should match the DataProviderReference
        /// element of a ProviderInfo additional data block.
        /// </summary>
        [XmlElement(DataType="token")]
        public string DataProviderReference {
            get {
                return this.dataProviderReferenceField;
            }
            set {
                this.dataProviderReferenceField = value;
            }
        }

        /// <summary>
        /// Contains information known by the service provider or device about the subscriber, e.g., Name,
        /// Address, Individual Telephone Number, Main Telephone Number, and any other data.
        /// </summary>
        [XmlArrayItem("vcard", Namespace="urn:ietf:params:xml:ns:vcard-4.0", IsNullable=false)]
        public vcardType[] SubscriberData {
            get {
                return this.subscriberDataField;
            }
            set {
                this.subscriberDataField = value;
            }
        }
        
        /// <summary>
        /// Extension point for this class.
        /// </summary>
        [XmlAnyElement()]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }

        /// <summary>
        /// If true, then the subscriber requests data privacy.The interpretation of this indicator is left 
        /// to each jurisdiction. See Section 4.4.1 of RFC 7852.
        /// </summary>
        [XmlAttribute()]
        public bool privacyRequested {
            get {
                return this.privacyRequestedField;
            }
            set {
                this.privacyRequestedField = value;
            }
        }
    }
}
